# -*- coding: utf-8 -*-
"""Music_Transcribing[NMF].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qY2xtGlblyKt0S8iVurOFY0glSPTH5zE

Библиотеки которые можно использовать: librosa, NMFToolbox, Nimfa, Mido/Pretty_midi,MIDIUtil.

Из всех библиотек с реализацией NMF пока остановился на Nimfa, не пойдет с ней - буду пробовать работать с NMFToolbox. Перед тем как запускать код дальше надо установить Nimfa.
"""

pip install nimfa

!grep -rl "np.mat" /usr/local/lib/python3.12/dist-packages/nimfa | xargs sed -i 's/np.mat/np.asmatrix/g'
!grep -rl "asmatrixrix" /usr/local/lib/python3.12/dist-packages/nimfa | xargs sed -i 's/asmatrixrix/asmatrix/g'
!grep -R "asmatrixrix" /usr/local/lib/python3.12/dist-packages/nimfa

"""Попробуем CQT вместо STFT, мб результаты будут лучше"""

import numpy as np
K = 3
def frec(p,K):
  return 440 * 2**((p*K-49*K)/(12*K))
def harmonic_template(p, coef=3, t=0.1):
  vec = np.zeros((88 * coef))
  fq = frec(p,1)
  fu = 440 * 2 ** (39/12)
  tpls = []
  m = int(np.floor(fu / fq))
  for fr in range(m):
    i_s = int(np.ceil(np.log2(((fq * (fr+1) * (1-t/2)) / 440)) * (12 * coef) + 49 * coef))
    i_f = int(np.floor(np.log2(((fq * (fr+1) * (1+t/2)) / 440)) * (12 * coef) + 49 * coef))
    for k in range(i_s-1,i_f):
      vec[k] = 1
  return vec

harmonic_template(49)

print(frec(69,1))

from scipy.io import wavfile
import numpy as np
import librosa
import nimfa
g = 2
HOP = 1024
K = 3
f_s, x = wavfile.read("/content/Prelude-in-E-Minor-Nr-4.wav")

def norm_log(H, gamma=5):
    return np.log1p(gamma * H)
def frec(p,K):
  return 440 * 2**((p*K-49*K)/(12*K))
def harmonic_template(p, coef=3, t=0.1):
  vec = np.zeros((88 * coef))
  fq = frec(p,1)
  fu = 440 * 2 ** (39/12)
  tpls = []
  m = int(np.floor(fu / fq))
  for fr in range(m):
    i_s = max(0,int(np.ceil(np.log2(((fq * (fr+1) * (1-t/2)) / 440)) * (12 * coef) + 49 * coef))-1)
    i_f = min(int(np.floor(np.log2(((fq * (fr+1) * (1+t/2)) / 440)) * (12 * coef) + 49 * coef)), 88 * coef)
    if(i_s==i_f):
      vec[i_s] = 1
    for k in range(i_s,i_f):
      vec[k] = 1
  return vec
def init_W(coef=3, t=0.1):
  vec = np.zeros((88 * coef, 88))
  for i in range(88):
    vec[:,i] = harmonic_template(i,coef,t)
  return vec

def sparsity(x, eps=1e-10):
    x = np.asarray(x).ravel()
    N = x.size

    if N <= 1:
        return 0.0  # not defined, fallback

    l2_norm = np.sqrt(np.sum(x**2)) + eps

    term = np.sum(np.tanh(np.abs(x)**2)) / l2_norm

    return (np.sqrt(N) - term) / (np.sqrt(N) - 1)

if(x.dtype==np.int32):
  x = x / (2**31)
elif(x.dtype==np.int16):
  x = x / (2**15)
else:
  raise ValueError(f"Unsupported sample type: {x.dtype}")
onsets = librosa.onset.onset_detect(y=x, sr=f_s, hop_length=HOP,units='frames')
nof_bins = int(np.floor(np.log2(f_s / (2 * librosa.note_to_hz('A0')))) * (12 * K))
print("nof_bins=",nof_bins)
spectrogram = np.abs(librosa.cqt(x,sr=f_s, fmin=librosa.note_to_hz('A0'), bins_per_octave=12 * K, n_bins=88 * K, hop_length=HOP))
#spectrogram = np.abs(librosa.cqt(x,sr=f_s, fmin=librosa.note_to_hz('A0'), bins_per_octave=12 * K, n_bins=nof_bins, hop_length=HOP))
spectrogram_norm = norm_log(spectrogram, g)
spectrogram_norm = librosa.util.normalize(spectrogram_norm, norm = 2, axis = 0, threshold = 0.05)

max_index = np.argmax(spectrogram_norm[:,onsets[0]+5])
print(max_index)  # 1
print(sparsity(spectrogram_norm[:,onsets[10]+5]))
#spectrogram_compressed = np.log(1+gamma*spectrogram)

W_i = init_W(3,0.08)
import matplotlib.pyplot as plt
plt.figure()
#plt.imshow(H_v, aspect='auto', origin='lower')
#plt.imshow(Y[:,140:160], aspect='auto', origin='lower')
plt.imshow(spectrogram_norm, aspect='auto', origin='lower')
#plt.imshow(W_i, aspect='auto', origin='lower')
#plt.imshow(Y, aspect='auto', origin='lower')
plt.colorbar()
plt.title("Activation matrix W")
plt.xlabel("Time frames")
plt.ylabel("Pitch / Component index")
plt.show()

def build_W0(sr,
             bins_per_octave,
             n_bins,
             fmin,
             n_harmonics=10,
             decay=1.0,
             sigma=1.5,
             inharmonicity=0.0):

    # CQT frequency grid (MUST match your spectrogram)
    freqs = librosa.cqt_frequencies(
        n_bins=n_bins,
        fmin=fmin,
        bins_per_octave=bins_per_octave
    )

    midi_notes = np.arange(21, 21 + 88)  # piano
    W0 = np.zeros((n_bins, len(midi_notes)))

    for i, m in enumerate(midi_notes):
        f0 = librosa.midi_to_hz(m)
        template = np.zeros(n_bins)

        for h in range(1, n_harmonics + 1):
            # optional piano inharmonicity
            fh = h * f0 * np.sqrt(1 + inharmonicity * h**2)

            if fh >= sr / 2:
                break

            # nearest bin
            idx = np.argmin(np.abs(freqs - fh))

            # Gaussian spread
            k = np.arange(n_bins)
            peak = np.exp(-(k - idx)**2 / (2 * sigma**2))

            template += (1 / (h ** decay)) * peak

        # normalize (critical)
        template /= np.linalg.norm(template) + 1e-10

        W0[:, i] = template

    return W0

W_0 = build_W0(sr=f_s, bins_per_octave=12*K, n_bins=88 * K, fmin=librosa.note_to_hz('A0'))
print(W_i)

print(W_i.shape)
import matplotlib.pyplot as plt
plt.figure()
#plt.imshow(H_v, aspect='auto', origin='lower')
#plt.imshow(Y[:,140:160], aspect='auto', origin='lower')
plt.imshow(W_0, aspect='auto', origin='lower')
#plt.imshow(W_i, aspect='auto', origin='lower')
#plt.imshow(Y, aspect='auto', origin='lower')
plt.colorbar()
plt.title("Activation matrix W")
plt.xlabel("Time frames")
plt.ylabel("Pitch / Component index")
plt.show()

H_0 = np.random.rand(88, spectrogram_norm.shape[1])
#nmf = nimfa.Nmf(spectrogram_compressed, seed='fixed', W=W_temp)
nmf = nimfa.Nmf(
    spectrogram_norm,
    rank=K,
    seed='fixed',
    W=W_0,
    H=H_0,
    max_iter=200,
    beta=1, sparsity=(None, 0.2),
    objective='div',
    update='divergence'
)
nmf_fit = nmf()
W_est = nmf_fit.basis()
H_est = nmf_fit.coef()

import matplotlib.pyplot as plt
plt.figure()
#plt.imshow(H_v, aspect='auto', origin='lower')
#plt.imshow(Y[:,140:160], aspect='auto', origin='lower')
plt.imshow(W_est, aspect='auto', origin='lower')
#plt.imshow(W_i, aspect='auto', origin='lower')
#plt.imshow(Y, aspect='auto', origin='lower')
plt.colorbar()
plt.title("Activation matrix W")
plt.xlabel("Time frames")
plt.ylabel("Pitch / Component index")
plt.show()

print(onsets)
print(len(onsets))

from scipy.ndimage import label
def enforce_min_duration(B, min_len=10):
    for q in range(B.shape[0]):
        labels, n = label(B[q])
        for i in range(1, n+1):
            if np.sum(labels == i) < min_len:
                B[q][labels == i] = 0
    return B
def matrix_filter(H):
  H_c = H.copy()
  for i in range(H_c.shape[0]):
    for j in range(H_c.shape[1]):
      v = 0
      if ((j-1)>=0):
        v += H_c[i,j-1]
      if((j+1)<H_c.shape[1]):
        v += H_c[i,j+1]
      v += H_c[i,j]
      v = v / 3
      H_c[i,j] = v
  return H_c
def rowwise_norm(H, eps=1e-8):
    Hn = H.copy()
    for q in range(H.shape[0]):
        m = np.max(Hn[q])
        if m > eps:
            Hn[q] /= m
    return Hn
#Y = norm_dynamic_range(H_new)
Y = rowwise_norm(H_est)
Y = matrix_filter(Y)
#Y = unsharp_matrix(Y)
#Y = np.maximum(0, Y)
#Y = freq_ftr(Y)
#Y = binarize_matrix(Y)
#Y = track_notes(Y)
Y = enforce_min_duration(Y)
import matplotlib.pyplot as plt
plt.figure()
#plt.imshow(H_v, aspect='auto', origin='lower')
#plt.imshow(Y[:,140:160], aspect='auto', origin='lower')
plt.imshow(Y, aspect='auto', origin='lower')
#plt.imshow(W_i, aspect='auto', origin='lower')
#plt.imshow(Y, aspect='auto', origin='lower')
plt.colorbar()
plt.title("Activation matrix W")
plt.xlabel("Time frames")
plt.ylabel("Pitch / Component index")
plt.show()

def pitch_energy(fp,p):
  en = 0
  en_t = np.sum(np.square(fp))
  h = pitch_harmonics(p)
  h = [m for m in h if m <= 87]
  alpha = -1
  #print(h)
  for l in range(len(h)):
    en += (l+2)**alpha * fp[h[l]]**2
    #print(l,h[l])
  #print(en)
  return float(en)
'''def transcribe_frame(fr,pol=9):
  peaks = [int(p) for p in top_k_indices(fr,20)]
  notes = []
  thr = np.median(fr,axis=0)
  thr += 0.1
  alpha = -1
  print(fr.shape)
  for p in peaks:
    #a = [p+12,p+19,p+24,p+28,p+31,p+34,p+36]
    if(fr[p]>thr):
      a = pitch_harmonics(p)
      sc = 0
      for pt in range(len(a)):
        if a[pt] in peaks:
          sc += (pt+2)**alpha
      #notes.append((p,float(fr[p,0]),len(set(a) & set(peaks))))
      #notes.append((p,float(fr[p,0]),sc))
      notes.append((p,pitch_energy(fr,p)))
  notes = sorted(notes, key=lambda x: x[1],reverse=True)
  return notes
  print(notes)'''
'''def top_k_indices(v, k):
    v = np.asarray(v).ravel()      # ensure 1D ndarray
    return np.argpartition(v, -k)[-k:]'''

def top_k_indices(v, k):
    v = np.asarray(v).ravel()          # ensure 1D
    idx = np.argpartition(v, -k)[-k:]  # indices of k largest elements
    idx = idx[np.argsort(v[idx])[::-1]]  # sort them by value (descending)
    return idx
def pitch_harmonics(p):
  r = [p+12,p+19,p+24,p+28,p+31,p+34,p+36]
  return [m for m in r if m <= 87]
def transcribe_frame(fr,thr=0.18):
  frn = fr.copy()
  peaks = [int(p) for p in top_k_indices(fr,20)]
  #peaks = [int(p) for p in range(88) if fr[p] > 0.25]
  peaks = sorted(peaks)
  #print(peaks)
  alpha = 0.3
  rv_start = 0.7
  #rv_start = 1
  notes = []
  for p in range(len(peaks)):
    frns = frn.copy()
    sc = 0
    en = fr[peaks[p]]
    pch = pitch_harmonics(peaks[p])
    ind = []
    for idx in range(len(pch)):
      if(frn[pch[idx]]>rv_start*(alpha)**idx):
        sc += 1/(idx+1)
        '''* float(frn[pch[idx]])**2'''
        frn[pch[idx]] -= rv_start*(alpha)**idx
        ind.append(idx)
    #score correction
    '''if(peaks[p]<=87):
      sc *= 2**((peaks[p] - 69) / 12)'''
    #sc *= float(frn[peaks[p]]/(np.max(frn)))
    #notes.append((peaks[p],sc))
    '''if(float(sc*fr[peaks[p]])<=thr):
      for i in ind:
        frn[pch[i]] += rv_start*(alpha)**i'''
    if(float(sc*fr[peaks[p]])<=thr):
      frn = frns
    notes.append((peaks[p],float(sc*fr[peaks[p]])))
  notes = sorted(notes, key=lambda x: x[1],reverse=True)
  notes = list(filter(lambda t: t[1] > thr, notes))
  return [t[0] for t in notes]
  #print(notes)

def transcribe_onset(m):
  st = np.zeros((88,))
  #ln = m.shape[1] // 2
  r = []
  #print("ln",ln)
  for j in range(m.shape[1]):
    for l in transcribe_frame(m[:,j]):
      st[l] +=1
  ap = [int(p) for p in top_k_indices(st,88)]
  s = 0
  summa = np.sum(st)
  for el in ap:
    s += st[el]
    if(s>=round((0.7 * summa)) or st[el]==0):
      break
    r.append(el)
    #print(el,st[el])
    #if(st[el]>ln):
    #  r.append(el)
  #print(np.sum(st))

  #print(st[ap[0]],st[ap[1]])
  #return ap
  #print(st[ap[0]],st[ap[1]])
  #print(st)
  return r
def transcribe_H(Y,os):
  tr = np.zeros(Y.shape)
  for idx in range(len(os)-1):
    nts = transcribe_onset(Y[:,os[idx]:os[idx]+10])
    for n in nts:
      tr[n,os[idx]:os[idx]+10] = 1
    for i in range(os[idx]+10,os[idx+1]):
      for n in nts:
        if(np.max(Y[n,i-4:i+4])>0.5):
          tr[n,i] = 1
        #else:
        #  nts.remove(n)
      #if(len(nts)==0):
        #break
  '''nts = transcribe_onset(Y[:,os[len(os)-1]:os[len(os)-1]+10])
  for n in nts:
    tr[n,os[len(os)-1]:os[len(os)-1]+10] = 1
  print(Y.shape[1])
  for i in range(os[len(os)-1]+10,Y.shape[1]-5):
    for n in nts:
      if(np.max(Y[n,i-4:i+5])>0.5):
        tr[n,i] = 1'''
  return tr

def pitch_energy(fp,p):
  en = 0
  en_t = np.sum(np.square(fp))
  h = pitch_harmonics(p)
  h = [m for m in h if m <= 87]
  #print(h)
  for l in h:
    en += fp[l]**2
  #print(en)
  return float(en/en_t)
  #return en[0,0]
#print(transcribe_frame(H_m[:,1]))
print(transcribe_onset(Y[:,479:489]))
#print(transcribe_frame(Y[:,152]))
#print(Y[38,203],Y[39,203])

trscrptn = transcribe_H(Y,onsets)
trscrptn[0,:] = 0
trscrptn = enforce_min_duration(trscrptn,min_len=10)
import matplotlib.pyplot as plt
plt.figure()
#plt.imshow(H_v, aspect='auto', origin='lower')
#plt.imshow(Y[:,140:160], aspect='auto', origin='lower')
#plt.imshow(Y[:,479:489], aspect='auto', origin='lower')
plt.imshow(trscrptn, aspect='auto', origin='lower')
#plt.imshow(Y, aspect='auto', origin='lower')
plt.colorbar()
plt.title("Activation matrix H")
plt.xlabel("Time frames")
plt.ylabel("Pitch / Component index")
plt.show()

"""**Читаем исходный файл**

# Оценка результатов транскрибирования
"""

pip install pretty_midi

import pretty_midi
midi = pretty_midi.PrettyMIDI("Prelude-in-E-Minor-Nr-4.mid")

pitches = set()

for instrument in midi.instruments:
    for note in instrument.notes:
        pitches.add(note.pitch)

#print(len(sorted(pitches)))
#print(len(sorted(sp_max)))
#print(len(set(sp_max) & set(pitches)))

import numpy as np
import pretty_midi

def midi_to_binary_matrix(
    midi_input,
    dt=0.02,                     # time quantum in seconds
    pitch_range=(21, 108),  # A0–C8 by default
    min_overlap=0.5         # fraction of frame that must be covered
):
    """
    Convert MIDI to binary (88 x T) note activation matrix using fixed time grid.

    A note is active in a frame if it overlaps the frame
    by at least min_overlap * dt.
    """

    if dt <= 0:
        raise ValueError("dt must be positive (seconds)")

    # Load MIDI
    if isinstance(midi_input, pretty_midi.PrettyMIDI):
        pm = midi_input
    else:
        pm = pretty_midi.PrettyMIDI(midi_input)

    # Time axis
    total_time = pm.get_end_time()
    T = int(np.ceil(total_time / dt))
    frame_times = np.arange(T) * dt

    n_pitches = pitch_range[1] - pitch_range[0] + 1
    B = np.zeros((n_pitches, T), dtype=np.uint8)

    # Process notes
    for instrument in pm.instruments:
        if instrument.is_drum:
            continue

        for note in instrument.notes:
            if not (pitch_range[0] <= note.pitch <= pitch_range[1]):
                continue

            p = note.pitch - pitch_range[0]

            start_frame = int(np.floor(note.start / dt))
            end_frame   = int(np.ceil(note.end   / dt))

            for t in range(start_frame, min(end_frame, T)):
                frame_start = t * dt
                frame_end   = frame_start + dt

                overlap = max(
                    0.0,
                    min(note.end, frame_end) - max(note.start, frame_start)
                )

                if overlap >= min_overlap * dt:
                    B[p, t] = 1

    return B, frame_times

# 20 ms frames (matches typical STFT hop ~512 @ 44.1kHz)
dt = 1024 / f_s
#print(dt)
#dt = 0.023
B, times = midi_to_binary_matrix(
    "Prelude-in-E-Minor-Nr-4.mid",
    dt=dt
)
print(B.shape,trscrptn.shape)
#print(H_v.shape, B.shape)   # (88, T)
import matplotlib.pyplot as plt
plt.figure()
#plt.imshow(H_v, aspect='auto', origin='lower')
plt.imshow(B, aspect='auto', origin='lower')
plt.colorbar()
plt.title("Activation matrix H")
plt.xlabel("Time frames")
plt.ylabel("Pitch / Component index")
plt.show()

def evaluate_results(H_et,H):
  #H_et - reference transcription of the piece
  #H - estimated transcription of the piece
  assert H_et.shape == H.shape
  P = 0
  R = 0
  F1 = 0
  TP = 0
  FP = 0
  FN = 0
  for i in range(H_et.shape[1]):
    TP += sum(1 for t, p in zip(H_et[:,i], H[:,i]) if t == 1 and p == 1)
    FP += sum(1 for t, p in zip(H_et[:,i], H[:,i]) if t == 0 and p == 1)
    FN += sum(1 for t, p in zip(H_et[:,i], H[:,i]) if t == 1 and p == 0)
  P = TP / (TP + FP)
  R = TP / (TP + FN)
  F1 = 2 * P * R / (P + R)
  return (P,R,F1)

a = [0,1,1,1,0]
b = [1,1,1,0,0]
def top_k_indices(v, k):
    v = np.asarray(v).ravel()      # ensure 1D ndarray
    return np.argpartition(v, -k)[-k:]
print(top_k_indices(b,3))

print(evaluate_results(trscrptn[:,:B.shape[1]],B))
#print(evaluate_results(trscrptn,B[:,:trscrptn.shape[1]]))
#print(trscrptn[:,B.shape[1]].shape)
#print(B.shape)