# -*- coding: utf-8 -*-
"""Music_Transcribing[NMF].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qY2xtGlblyKt0S8iVurOFY0glSPTH5zE

Библиотеки которые можно использовать: librosa, NMFToolbox, Nimfa, Mido/Pretty_midi,MIDIUtil.

Из всех библиотек с реализацией NMF пока остановился на Nimfa, не пойдет с ней - буду пробовать работать с NMFToolbox. Перед тем как запускать код дальше надо установить Nimfa.
"""

pip install nimfa

!grep -rl "np.mat" /usr/local/lib/python3.12/dist-packages/nimfa | xargs sed -i 's/np.mat/np.asmatrix/g'
!grep -rl "asmatrixrix" /usr/local/lib/python3.12/dist-packages/nimfa | xargs sed -i 's/asmatrixrix/asmatrix/g'
!grep -R "asmatrixrix" /usr/local/lib/python3.12/dist-packages/nimfa

"""Попробуем CQT вместо STFT, мб результаты будут лучше"""

from scipy.io import wavfile
import numpy as np
import librosa
import nimfa
g = 2
HOP = 1024
K = 3
f_s, x = wavfile.read("/content/Prelude-in-E-Minor-Nr-4.wav")

def norm_log(H, gamma=5):
    return np.log1p(gamma * H)
def harmonic_template(coef=3):
  #this should contain harmonic template with nearest frequencies of harmonics for coef*88-length vector
if(x.dtype==np.int32):
  x = x / (2**31)
elif(x.dtype==np.int16):
  x = x / (2**15)
else:
  raise ValueError(f"Unsupported sample type: {x.dtype}")
onsets = librosa.onset.onset_detect(y=x, sr=f_s, hop_length=HOP,units='frames')
spectrogram = np.abs(librosa.cqt(x, fmin=librosa.note_to_hz('A0'), bins_per_octave=12 * K, n_bins=88 * K, hop_length=HOP))
spectrogram_norm = norm_log(spectrogram, g)
spectrogram_norm = librosa.util.normalize(spectrogram_norm, norm = 2, axis = 0, threshold = 0.05)
print(np.max(spectrogram_norm))
#spectrogram_compressed = np.log(1+gamma*spectrogram)


import matplotlib.pyplot as plt
plt.figure()
#plt.imshow(H_v, aspect='auto', origin='lower')
#plt.imshow(Y[:,140:160], aspect='auto', origin='lower')
plt.imshow(spectrogram_norm, aspect='auto', origin='lower')
#plt.imshow(Y, aspect='auto', origin='lower')
plt.colorbar()
plt.title("Activation matrix H")
plt.xlabel("Time frames")
plt.ylabel("Pitch / Component index")
plt.show()

"""**Читаем исходный файл**"""

from scipy.io import wavfile
import numpy as np
import librosa
import nimfa
gamma = 100
fft_bins = 2048
onsets_mode = True
if(onsets_mode):
  pitch_count = 88 * 2
else:
  pitch_count = 88
f_s, x = wavfile.read("/content/Prelude-in-E-Minor-Nr-4.wav")
print(f_s)        # sample rate
print(x.dtype)   # int16, int32, etc.
print(x.shape)   # (N,) mono or (N, channels)
#print(x[100000])
def init_nmf_template_pitch(K, pitch_set, freq_res, tol_pitch=0.05):
    """Initializes template matrix for a given set of pitches

    Notebook: C8/C8S3_NMFSpecFac.ipynb

    Args:
        K (int): Number of frequency points
        pitch_set (np.ndarray): Set of fundamental pitches
        freq_res (float): Frequency resolution
        tol_pitch (float): Relative frequency tolerance for the harmonics (Default value = 0.05)

    Returns:
        W (np.ndarray): Nonnegative matrix of size K x R with R = len(pitch_set)
    """
    R = len(pitch_set)
    W = np.zeros((K, R))
    for r in range(R):
        W[:, r] = template_pitch(K, pitch_set[r], freq_res, tol_pitch=tol_pitch)
    return W
def init_nmf_template_pitch_onset(K, pitch_set, freq_res, tol_pitch=0.05):
    """Initializes template matrix with onsets for a given set of pitches

    Notebook: C8/C8S3_NMFSpecFac.ipynb

    Args:
        K (int): Number of frequency points
        pitch_set (np.ndarray): Set of fundamental pitches
        freq_res (float): Frequency resolution
        tol_pitch (float): Relative frequency tolerance for the harmonics (Default value = 0.05)

    Returns:
        W (np.ndarray): Nonnegative matrix of size K x (2R) with R = len(pitch_set)
    """
    R = len(pitch_set)
    W = np.zeros((K, 2*R))
    for r in range(R):
        W[:, 2*r] = 0.1
        W[:, 2*r+1] = template_pitch(K, pitch_set[r], freq_res, tol_pitch=tol_pitch)
    return W
def sparse_H(H,onsets):
  H_r = H.copy()
  for i in range(H_r.shape[1]):
    if(i in onsets or (i-1) in onsets or (i-2) in onsets):
      H[1::2,i] = 0
    else:
      H[0::2,i] = 0
  return H_r
def template_pitch(K, pitch, freq_res, tol_pitch=0.05):
    """Defines spectral template for a given pitch

    Notebook: C8/C8S3_NMFSpecFac.ipynb

    Args:
        K (int): Number of frequency points
        pitch (float): Fundamental pitch
        freq_res (float): Frequency resolution
        tol_pitch (float): Relative frequency tolerance for the harmonics (Default value = 0.05)

    Returns:
        template (np.ndarray): Nonnegative template vector of size K
    """
    max_freq = K * freq_res
    pitch_freq = 2**((pitch - 69) / 12) * 440
    max_order = int(np.ceil(max_freq / ((1 - tol_pitch) * pitch_freq)))
    #print(max_freq,pitch_freq,max_order)
    template = np.zeros(K)
    for m in range(1, max_order + 1):
        min_idx = max(0, int((1 - tol_pitch) * m * pitch_freq / freq_res))
        max_idx = min(K-1, int((1 + tol_pitch) * m * pitch_freq / freq_res))
        template[min_idx:max_idx+1] = 1 / m
    return template

if(x.dtype==np.int32):
  x = x / (2**31)
elif(x.dtype==np.int16):
  x = x / (2**15)
else:
  raise ValueError(f"Unsupported sample type: {x.dtype}")
onsets = librosa.onset.onset_detect(y=x, sr=f_s, hop_length=fft_bins//2,units='frames')

print(onsets)
spectrogram = np.abs(librosa.stft(x, n_fft=fft_bins,hop_length=fft_bins//2))
for i in range(spectrogram.shape[0]):
  spectrogram[i,:] *= (f_s / 2 * fft_bins)
spectrogram_compressed = np.log(1+gamma*spectrogram)
pitches = [x+21 for x in range(88)]
freq_res = f_s/(2 * (fft_bins//2+1))

if(onsets_mode):
  W_temp = init_nmf_template_pitch_onset(fft_bins//2+1,pitches,freq_res)
else:
  W_temp = init_nmf_template_pitch(fft_bins//2+1,pitches,freq_res)
#W_temp = np.random.rand(spectrogram_compressed.shape[0],88)
H_temp = np.random.rand(pitch_count, spectrogram_compressed.shape[1])
if(onsets_mode):
  H_temp = sparse_H(H_temp,onsets)
#nmf = nimfa.Nmf(spectrogram_compressed, seed='fixed', W=W_temp)
print(W_temp.shape)
print(H_temp.shape)
nmf = nimfa.Nmf(
    spectrogram_compressed,
    rank=pitch_count,
    seed='fixed',
    W=W_temp,
    H=H_temp,
    max_iter=200,
    beta=1, sparsity=(None, 0.2),
    objective='div'
)
nmf_fit = nmf()
W_est = nmf_fit.basis()
H_est = nmf_fit.coef()

if(onsets_mode):
  H_new = H_est[1::2]
else:
  H_new = H_est.copy()



import matplotlib.pyplot as plt
plt.figure()
#plt.imshow(H_v, aspect='auto', origin='lower')
W_n = W_est[:,1::2]
W_n_vis = np.log(1+100*W_n)
plt.imshow(W_n_vis, aspect='auto', origin='lower')
plt.colorbar()
plt.title("Activation matrix H")
plt.xlabel("Time frames")
plt.ylabel("Pitch / Component index")
plt.show()
print(W_n_vis[:,0])


import matplotlib.pyplot as plt

plt.plot(W_n_vis[:,10])
plt.show()

print(len(res))
print(type(x))
print(x.shape)
print(x.dtype)
print(np.min(x), np.max(x))
print(np.isnan(x).any(), np.isinf(x).any())

from scipy.ndimage import label
from scipy.ndimage import gaussian_filter1d
tempo, beats = librosa.beat.beat_track(y=x, sr=f_s)

tempo = float(tempo)          # or: tempo = tempo.item()

print(f"Estimated tempo: {tempo:.2f} BPM")

beat_times = librosa.frames_to_time(beats, sr=f_s)
beat_frames = list(map(int, beat_times * f_s / 1024))
print("beat_frames=",beat_frames)
print(f"Beat positions (sec.): {beat_times}")

def norm_dynamic_range(H):
  H_min = np.min(H)
  H_max = np.max(H)
  H_mean = np.mean(H)
  Z = (H-H_mean)/(H_max-H_min)
  Y = 1 / (1+np.exp(-Z))
  return Y
def transcribe_frame(fr,thr=0.1,pol=9):
  peaks = top_k_indices(fr,20)
  notes = []
  for p in peaks:
    a = [p+12,p+19,p+24,p+28,p+31,p+34,p+36]
    notes.add((p,len(a & peaks)))

  sorted(list_of_tuples, key=lambda x: x[1])
def matrix_filter(H):
  H_c = H.copy()
  for i in range(H_c.shape[0]):
    for j in range(H_c.shape[1]):
      v = 0
      if ((j-1)>=0):
        v += H_c[i,j-1]
      if((j+1)<H_c.shape[1]):
        v += H_c[i,j+1]
      v += H_c[i,j]
      v = v / 3
      H_c[i,j] = v
  return H_c

def enforce_min_duration(B, min_len=10):
    for q in range(B.shape[0]):
        labels, n = label(B[q])
        for i in range(1, n+1):
            if np.sum(labels == i) < min_len:
                B[q][labels == i] = 0
    return B

def rowwise_norm(H, eps=1e-8):
    Hn = H.copy()
    for q in range(H.shape[0]):
        m = np.max(Hn[q])
        if m > eps:
            Hn[q] /= m
    return Hn
def find_local_max(Y):
  mx = []
  for i in range(1,Y.shape[0]):
    v = np.max(Y[i,:])
    if(v > 0.922):
      mx.append(i)
  return mx
def maximize_h(H,onsets):
  maxlist = []
  for i in range(len(onsets)-1):
    cur_max = onsets[i]
    for j in range(onsets[i],onsets[i+1]):
      if(np.std(np.array(H[:,cur_max])) < np.std(np.array(H[:,j]))):
        cur_max = j
    maxlist.append(cur_max)
  return H[:,maxlist]

def unsharp_mask_mean(x, window=5, amount=1.0):
    """
    Simple mean-value unsharp masking of a 1D vector.

    Parameters
    ----------
    x : array-like
        Input vector.
    window : int
        Size of moving average window.
    amount : float
        Sharpening strength.

    Returns
    -------
    y : numpy array
        Sharpened vector.
    """

    x = np.asarray(x, dtype=float).ravel()

    kernel = np.ones(window) / window
    blurred = np.convolve(x, kernel, mode='same')

    detail = x - blurred
    y = x + amount * detail

    return y
def unsharp_matrix(Y):
  Y_c = np.zeros(Y.shape)
  for i in range(Y.shape[1]):
    #print(np.array(Y[:,i]))
    Y_c[:,i] = unsharp_mask_mean(np.array(Y[:,i]))
  return Y_c
#Y = norm_dynamic_range(H_new)
Y = rowwise_norm(H_new)
Y = matrix_filter(Y)
#Y = unsharp_matrix(Y)
#Y = np.maximum(0, Y)
#Y = freq_ftr(Y)
#Y = binarize_matrix(Y)
#Y = track_notes(Y)
Y = enforce_min_duration(Y)
#Y[0,:] = 0
#H_v = np.asarray(H_v)
#H_v = beat_sync_H(H_v,beat_frames)
#print(res)

#H_v = generate_transcription(H_v,res)
#H_v = enforce_min_duration(H_v)

H_m = maximize_h(Y,onsets)

import matplotlib.pyplot as plt
plt.figure()
#plt.imshow(H_v, aspect='auto', origin='lower')
#plt.imshow(Y[:,140:160], aspect='auto', origin='lower')
plt.imshow(H_m, aspect='auto', origin='lower')
#plt.imshow(Y, aspect='auto', origin='lower')
plt.colorbar()
plt.title("Activation matrix H")
plt.xlabel("Time frames")
plt.ylabel("Pitch / Component index")
plt.show()


print(find_local_max(Y))
print(len(find_local_max(Y)))
sp_max = find_local_max(Y)
print(sp_max)
print(len(sp_max))
#print(maximize_h(Y,onsets))
#print(maximize_h(H_m,onsets))

def pitch_energy(fp,p):
  en = 0
  en_t = np.sum(np.square(fp))
  h = pitch_harmonics(p)
  h = [m for m in h if m <= 87]
  alpha = -1
  #print(h)
  for l in range(len(h)):
    en += (l+2)**alpha * fp[h[l]]**2
    #print(l,h[l])
  #print(en)
  return float(en)
'''def transcribe_frame(fr,pol=9):
  peaks = [int(p) for p in top_k_indices(fr,20)]
  notes = []
  thr = np.median(fr,axis=0)
  thr += 0.1
  alpha = -1
  print(fr.shape)
  for p in peaks:
    #a = [p+12,p+19,p+24,p+28,p+31,p+34,p+36]
    if(fr[p]>thr):
      a = pitch_harmonics(p)
      sc = 0
      for pt in range(len(a)):
        if a[pt] in peaks:
          sc += (pt+2)**alpha
      #notes.append((p,float(fr[p,0]),len(set(a) & set(peaks))))
      #notes.append((p,float(fr[p,0]),sc))
      notes.append((p,pitch_energy(fr,p)))
  notes = sorted(notes, key=lambda x: x[1],reverse=True)
  return notes
  print(notes)'''
'''def top_k_indices(v, k):
    v = np.asarray(v).ravel()      # ensure 1D ndarray
    return np.argpartition(v, -k)[-k:]'''

def top_k_indices(v, k):
    v = np.asarray(v).ravel()          # ensure 1D
    idx = np.argpartition(v, -k)[-k:]  # indices of k largest elements
    idx = idx[np.argsort(v[idx])[::-1]]  # sort them by value (descending)
    return idx
def pitch_harmonics(p):
  r = [p+12,p+19,p+24,p+28,p+31,p+34,p+36]
  return [m for m in r if m <= 87]
def transcribe_frame(fr,thr=0.25):
  frn = fr.copy()
  peaks = [int(p) for p in top_k_indices(fr,20)]
  #peaks = [int(p) for p in range(88) if fr[p] > 0.25]
  peaks = sorted(peaks)
  #print(peaks)
  alpha = 0.5
  rv_start = 0.7
  #rv_start = 1
  notes = []
  for p in range(len(peaks)):
    frns = frn.copy()
    sc = 0
    en = fr[peaks[p]]
    pch = pitch_harmonics(peaks[p])
    ind = []
    for idx in range(len(pch)):
      if(frn[pch[idx]]>rv_start*(alpha)**idx):
        sc += 1/(idx+1)
        '''* float(frn[pch[idx]])**2'''
        frn[pch[idx]] -= rv_start*(alpha)**idx
        ind.append(idx)
    #score correction
    '''if(peaks[p]<=87):
      sc *= 2**((peaks[p] - 69) / 12)'''
    #sc *= float(frn[peaks[p]]/(np.max(frn)))
    #notes.append((peaks[p],sc))
    '''if(float(sc*fr[peaks[p]])<=thr):
      for i in ind:
        frn[pch[i]] += rv_start*(alpha)**i'''
    if(float(sc*fr[peaks[p]])<=thr):
      frn = frns
    notes.append((peaks[p],float(sc*fr[peaks[p]])))
  notes = sorted(notes, key=lambda x: x[1],reverse=True)
  notes = list(filter(lambda t: t[1] > thr, notes))
  return [t[0] for t in notes]
  #print(notes)

def transcribe_onset(m):
  st = np.zeros((88,))
  #ln = m.shape[1] // 2
  r = []
  #print("ln",ln)
  for j in range(m.shape[1]):
    for l in transcribe_frame(m[:,j]):
      st[l] +=1
  ap = [int(p) for p in top_k_indices(st,88)]
  s = 0
  summa = np.sum(st)
  for el in ap:
    s += st[el]
    if(s>=round((0.7 * summa)) or st[el]==0):
      break
    r.append(el)
    #print(el,st[el])
    #if(st[el]>ln):
    #  r.append(el)
  #print(np.sum(st))

  #print(st[ap[0]],st[ap[1]])
  #return ap
  #print(st[ap[0]],st[ap[1]])
  #print(st)
  return r
def transcribe_H(Y,os):
  tr = np.zeros(Y.shape)
  for idx in range(len(os)-1):
    nts = transcribe_onset(Y[:,os[idx]:os[idx]+10])
    for n in nts:
      tr[n,os[idx]:os[idx]+10] = 1
    for i in range(os[idx]+10,os[idx+1]):
      for n in nts:
        if(np.max(Y[n,i-4:i+4])>0.5):
          tr[n,i] = 1
        #else:
        #  nts.remove(n)
      #if(len(nts)==0):
        #break
  '''nts = transcribe_onset(Y[:,os[len(os)-1]:os[len(os)-1]+10])
  for n in nts:
    tr[n,os[len(os)-1]:os[len(os)-1]+10] = 1
  print(Y.shape[1])
  for i in range(os[len(os)-1]+10,Y.shape[1]-5):
    for n in nts:
      if(np.max(Y[n,i-4:i+5])>0.5):
        tr[n,i] = 1'''
  return tr

def pitch_energy(fp,p):
  en = 0
  en_t = np.sum(np.square(fp))
  h = pitch_harmonics(p)
  h = [m for m in h if m <= 87]
  #print(h)
  for l in h:
    en += fp[l]**2
  #print(en)
  return float(en/en_t)
  #return en[0,0]
#print(transcribe_frame(H_m[:,1]))
print(transcribe_onset(Y[:,479:489]))
#print(transcribe_frame(Y[:,152]))
#print(Y[38,203],Y[39,203])

trscrptn = transcribe_H(Y,onsets)
trscrptn[0,:] = 0
trscrptn = enforce_min_duration(trscrptn,min_len=10)
import matplotlib.pyplot as plt
plt.figure()
#plt.imshow(H_v, aspect='auto', origin='lower')
#plt.imshow(Y[:,140:160], aspect='auto', origin='lower')
#plt.imshow(Y[:,479:489], aspect='auto', origin='lower')
plt.imshow(trscrptn, aspect='auto', origin='lower')
#plt.imshow(Y, aspect='auto', origin='lower')
plt.colorbar()
plt.title("Activation matrix H")
plt.xlabel("Time frames")
plt.ylabel("Pitch / Component index")
plt.show()

m = trscrptn[:,138:150]
print(np.min(m), np.max(m))
print(np.unique(m))
print(trscrptn.shape)
import matplotlib.pyplot as plt
plt.imshow(m, aspect='auto', origin='lower')
plt.colorbar()
plt.title("Activation matrix H")
plt.xlabel("Time frames")
plt.ylabel("Pitch / Component index")
plt.show()
print(m[:,2])

def pitch_energy(fp,p):
  en = 0
  en_t = np.sum(np.square(fp))
  h = pitch_harmonics(p)
  h = [m for m in h if m <= 87]
  alpha = -1
  #print(h)
  for l in range(len(h)):
    en += (l+2)**alpha * fp[h[l]]**2
    #print(l,h[l])
  #print(en)
  return float(en)
  #return float(en/en_t)
'''def pitch_energy(fp,p):
  en = 0
  en_t = np.sum(np.square(fp))
  h = [pitch_harmonics(p) for p in pc]
  h = [m for m in h if m <= 87]
  #print(h)
  for l in h:
    en += fp[l]**2
  #print(en)
  return float(en/en_t)'''
  #return en[0,0]
def transcribe_frame(fr,pol=9):
  #peaks = [int(p) for p in top_k_indices(fr,10)]
  #peaks = [int(p) for p in range(88) if fr[p]>(1/3) * np.max(fr)]
  peaks = [p for p in range(1,87) if fr[p]>0.1 * np.max(fr)]
  #peaks = [int(p) for p in top_k_indices(fr,20)]
  notes = []
  alpha = -1
  #thr = 0.33 * np.max(fr,axis=0)
  for p in peaks:
    a = pitch_harmonics(p)
    sc = 0
    for pt in range(len(a)):
      if a[pt] in peaks:
        sc += (pt+2)**alpha
    if(sc > 0 and fr[p]>0.2):
      #notes.append((p,float(fr[p,0]),sc))
      #notes.append((p,pitch_energy(fr[:,0],p),sc))
      notes.append((p,sc,float(fr[p])))
  notes = sorted(notes, key=lambda x: x[1],reverse=True)
  return notes
  print(notes)
print(transcribe_frame(H_m[:,4]))
#print(transcribe_frame(Y[:,155]))
#print(transcribe_frame(Y[:,384]))
#print(pitch_energy(Y[:,152],50))
print(np.sum(np.square(Y[:, 152])))
#print(Y[:,152].shape)
print(Y[38,203],Y[39,203])

pc = [6,8,10,21]
h = [pitch_harmonics(p) for p in pc]
fh = list(set([item for sublist in h for item in sublist]))
print(sorted(fh))

print(H_v)

"""# Попробуем готовый NMFD"""

from scipy.io import wavfile
import numpy as np
import librosa
from convolutive_MM import convlutive_MM
import torch
from torchnmf.nmf import NMFD
gamma = 1
f_s, x = wavfile.read("/content/FChopinPreludeOp28n4.wav")
if(x.dtype==np.int32):
  x = x / (2**31)
elif(x.dtype==np.int16):
  x = x / (2**15)
else:
  raise ValueError(f"Unsupported sample type: {x.dtype}")
X = np.abs(librosa.stft(x, n_fft=2048,hop_length=1024))
print(f_s)        # sample rate
print(x.dtype)   # int16, int32, etc.
print(x.shape)   # (N,) mono or (N, channels)
print(x[100000])
def cnmf(V, n_components=8, n_lags=10, n_iter=100, eps=1e-9):
    """
    V: (F, T) non-negative matrix (e.g. magnitude spectrogram)
    W: (F, K, L)
    H: (K, T)
    """
    F, T = V.shape
    K = n_components
    L = n_lags

    # initialize
    W = np.random.rand(F, K, L)
    H = np.random.rand(K, T)

    for it in range(n_iter):
        print("Iteration number:",it)
        # reconstruct V_hat
        V_hat = np.zeros_like(V)
        for k in range(K):
            for l in range(L):
                V_hat[:, l:] += np.outer(W[:, k, l], H[k, :-l or None])

        # update H
        for k in range(K):
            num = np.zeros(T)
            den = np.zeros(T) + eps
            for l in range(L):
                Wkl = W[:, k, l][:, None]
                num[l:] += (Wkl * V[:, l:]).sum(axis=0)
                den[l:] += (Wkl * V_hat[:, l:]).sum(axis=0)
            H[k] *= num / den

        # update W
        for k in range(K):
            for l in range(L):
                num = (V[:, l:] * H[k, :-l or None]).sum(axis=1)
                den = (V_hat[:, l:] * H[k, :-l or None]).sum(axis=1) + eps
                W[:, k, l] *= num / den

        if it % 10 == 0:
            err = np.linalg.norm(V - V_hat)
            print(f"iter {it:3d} | error {err:.3f}")

    return W, H
#res = cnmf(X,88,10,100,eps=1e-9)
S = torch.from_numpy(X).float().unsqueeze(0)
model = NMFD(S.shape, rank=88, T=10)  # rank = components, T = time lags
model.fit(S, max_iter=200)
# Extract factors
W = model.W.detach().cpu().numpy()  # (F, rank, T)
H = model.H.detach().cpu().numpy()  # (batch, rank, time)

# Remove batch dimension from H
H = H[0]

pip install torchnmf

print(H.shape)
print(H[:,100])

import matplotlib.pyplot as plt

vmax = np.percentile(H, 99)

plt.figure(figsize=(10,4))
plt.imshow(
    H,
    aspect='auto',
    origin='lower',
    cmap='magma',
    vmin=0,
    vmax=vmax
)
plt.colorbar()
plt.title("CNMF activations (H) – clipped at 99th percentile")
plt.show()

"""# Пробуем CNMF (имплементация из libnmfd)"""

pip install libnmfd



"""# Обнаружение начал нот (Onsets detection)

Будем использовать подход, называемый Spectral Difference, вычисляя результат по формуле вот отсюда: https://www.iro.umontreal.ca/~pift6080/H09/documents/presentations/xavier_bello_tutorial.pdf
"""

def H(x):
  return (x+abs(x))/2
def summf(v1,v2):
  #v1 - spectral coefficients vector at moment n
  #v2 - spectral coefficients vector at moment (n+1)
  l = v1.shape[0]
  assert l == v2.shape[0]
  s = 0
  for i in range(l):
    s += (H(v2[i]-v1[i]))**2
  return s
def spec_diff(sp):
  res = []
  for i in range(sp.shape[1]-1):
    res.append(float(summf(sp[:,i],sp[:,i+1])))
  return res
H(5)
def eval_thrshld(d,n,M=100,abs_thrsh=0.1,lam=1.0):
  r = abs_thrsh
  n_s = n-M
  n_f = n+M
  if(n<M):
    n_s = M
  if(n+M>=len(d)):
    n_f = len(d)
  r += lam * np.median(d[n_s:n_f])
  return r
'''def peak_detect(data):
  res = np.zeros((len(data),))
  lval = 0
  for i in range(len(data)):
    if(data[i]>=eval_thrshld(data,i) and (i-lval)>=20):
      res[i] = 1
      lval = i
  return res'''
def peak_detect(data):
  #res = np.zeros((len(data),))
  res = []
  lval = 0
  for i in range(len(data)):
    if(data[i]>=eval_thrshld(data,i) and (i-lval)>=20):
      res.append(i)
      lval = i
  return res
data = spec_diff(spectrogram_compressed)
res = peak_detect(data)
def sparse_H(H,onsets):
  H_r = H.copy()
  for i in range(H_r.shape[1]):
    if(i in onsets or (i-1) in onsets or (i+1) in onsets):
      H[1::2,i] = 0
    else:
      H[0::2,i] = 0
  return H_r
print(res)
import matplotlib.pyplot as plt

import numpy as np
def shift_right(x, k):
    if(k==0):
      return x
    y = np.zeros_like(x)
    y[k:] = x[:-k]
    return y
def note_template(pitch, alpha=0.5):
  r = np.zeros((88,))
  #first eight harmonics of some pitch
  l = [0,12,19,24,28,31,34,36]
  r[l]=1
  #print(pitch)
  r = shift_right(r,pitch)
  return r
def top_k_indices(v, k):
    return np.argsort(v)[-k:][::-1]
def rms(x):
    return np.sqrt(np.mean(np.square(x)))
def process_frame(s,k=3,en_thrsh=0.4):
    assert s.shape[0] == 88 and s.shape[1] == 1
    notes = []
    s_c = s.copy()
    s_c = np.asarray(s, dtype=float).squeeze()
    #print(type(s_c))
    #print("s_c=",s_c)
    s_pitches = top_k_indices(s_c,k)
    #print("s_pitches=",s_pitches)
    for l in s_pitches:
      #print(l)
      r = rms(np.dot(note_template(l),s_c))
      #print("r=",r)
      if(r>en_thrsh):
        notes.append(int(l))
    return notes
def note_tracking(mtr):
  r = np.zeros(mtr.shape)
  for i in range(mtr.shape[1]):
    ind = process_frame(mtr[:,i])
    for k in ind:
      r[k,i] = 1
  return r

def note_tracking_paper_style(H, delta=0.1, win=10):
    Q, T = H.shape
    R = np.zeros_like(H, dtype=np.uint8)

    # 1. Per-pitch normalization (critical)
    '''keepdims=True'''
    Hn = H / (np.max(H, axis=1) + 1e-9)

    for q in range(Q):
        for t in range(T):

            # local mean (zero-padded)
            t0 = max(0, t - win)
            t1 = min(T, t + win + 1)
            local_mean = np.mean(Hn[q, t0:t1])

            # adaptive threshold
            thresh = local_mean + delta

            # onset condition (THIS is what you missed)
            if (
                Hn[q, t] > thresh and
                (t == 0 or Hn[q, t] > Hn[q, t - 1])
            ):
                R[q, t] = 1

    return R
H_n = np.log(1+H_est)
print(H_n.shape)
#H_n = note_tracking(H_n)
print(H_n.shape)
print(H_n[:,100].shape)

plt.figure()
#plt.imshow(np.log(1+200*H_est[1::2]), aspect='auto', origin='lower')
plt.imshow(note_tracking_paper_style(H_est), aspect='auto', origin='lower')
plt.colorbar()
plt.title("Activation matrix H")
plt.xlabel("Time frames")
plt.ylabel("Pitch / Component index")
plt.show()



def pitch_energy_compensation(H, gamma=0.7):
    """
    H: shape (88, T)
    """
    pitches = np.arange(88)
    weights = 2 ** (gamma * pitches / 12)
    weights = weights / weights.mean()  # normalize

    return H * weights[:, None]
H_n = np.log(1+H_est)
H_n = pitch_energy_compensation(H_n[1::2])
print(H_n.shape)
H_n = note_tracking(H_est)
print(H_n.shape)
print(H_n[:,100].shape)

plt.figure()
#plt.imshow(np.log(1+200*H_est[1::2]), aspect='auto', origin='lower')
plt.imshow(H_n, aspect='auto', origin='lower')
plt.colorbar()
plt.title("Activation matrix H")
plt.xlabel("Time frames")
plt.ylabel("Pitch / Component index")
plt.show()

print(H_s.shape)

print(note_template(0))

v=[3,7,5,2,7,8,9,1,2,3,5,6,7,8,9,2,]
def top_k_indices(v, k):
    return np.argsort(v)[-k:][::-1]
print(top_k_indices(v, 9))

"""# Оценка результатов транскрибирования"""

pip install pretty_midi

import pretty_midi
midi = pretty_midi.PrettyMIDI("Prelude-in-E-Minor-Nr-4.mid")

pitches = set()

for instrument in midi.instruments:
    for note in instrument.notes:
        pitches.add(note.pitch)

print(len(sorted(pitches)))
print(len(sorted(sp_max)))
print(len(set(sp_max) & set(pitches)))

import numpy as np
import pretty_midi

def midi_to_binary_matrix(
    midi_input,
    dt=0.02,                     # time quantum in seconds
    pitch_range=(21, 108),  # A0–C8 by default
    min_overlap=0.5         # fraction of frame that must be covered
):
    """
    Convert MIDI to binary (88 x T) note activation matrix using fixed time grid.

    A note is active in a frame if it overlaps the frame
    by at least min_overlap * dt.
    """

    if dt <= 0:
        raise ValueError("dt must be positive (seconds)")

    # Load MIDI
    if isinstance(midi_input, pretty_midi.PrettyMIDI):
        pm = midi_input
    else:
        pm = pretty_midi.PrettyMIDI(midi_input)

    # Time axis
    total_time = pm.get_end_time()
    T = int(np.ceil(total_time / dt))
    frame_times = np.arange(T) * dt

    n_pitches = pitch_range[1] - pitch_range[0] + 1
    B = np.zeros((n_pitches, T), dtype=np.uint8)

    # Process notes
    for instrument in pm.instruments:
        if instrument.is_drum:
            continue

        for note in instrument.notes:
            if not (pitch_range[0] <= note.pitch <= pitch_range[1]):
                continue

            p = note.pitch - pitch_range[0]

            start_frame = int(np.floor(note.start / dt))
            end_frame   = int(np.ceil(note.end   / dt))

            for t in range(start_frame, min(end_frame, T)):
                frame_start = t * dt
                frame_end   = frame_start + dt

                overlap = max(
                    0.0,
                    min(note.end, frame_end) - max(note.start, frame_start)
                )

                if overlap >= min_overlap * dt:
                    B[p, t] = 1

    return B, frame_times

# 20 ms frames (matches typical STFT hop ~512 @ 44.1kHz)
dt = 1024 / f_s
#print(dt)
#dt = 0.023
B, times = midi_to_binary_matrix(
    "Prelude-in-E-Minor-Nr-4.mid",
    dt=dt
)
print(B.shape,trscrptn.shape)
#print(H_v.shape, B.shape)   # (88, T)
import matplotlib.pyplot as plt
plt.figure()
#plt.imshow(H_v, aspect='auto', origin='lower')
plt.imshow(B, aspect='auto', origin='lower')
plt.colorbar()
plt.title("Activation matrix H")
plt.xlabel("Time frames")
plt.ylabel("Pitch / Component index")
plt.show()

def evaluate_results(H_et,H):
  #H_et - reference transcription of the piece
  #H - estimated transcription of the piece
  assert H_et.shape == H.shape
  P = 0
  R = 0
  F1 = 0
  TP = 0
  FP = 0
  FN = 0
  for i in range(H_et.shape[1]):
    TP += sum(1 for t, p in zip(H_et[:,i], H[:,i]) if t == 1 and p == 1)
    FP += sum(1 for t, p in zip(H_et[:,i], H[:,i]) if t == 0 and p == 1)
    FN += sum(1 for t, p in zip(H_et[:,i], H[:,i]) if t == 1 and p == 0)
  P = TP / (TP + FP)
  R = TP / (TP + FN)
  F1 = 2 * P * R / (P + R)
  return (P,R,F1)

a = [0,1,1,1,0]
b = [1,1,1,0,0]
def top_k_indices(v, k):
    v = np.asarray(v).ravel()      # ensure 1D ndarray
    return np.argpartition(v, -k)[-k:]
print(top_k_indices(b,3))

print(evaluate_results(trscrptn[:,:B.shape[1]],B))
#print(evaluate_results(trscrptn,B[:,:trscrptn.shape[1]]))
#print(trscrptn[:,B.shape[1]].shape)
#print(B.shape)

evaluate_results(H_f[:,:B.shape[1]],B)

"""Оценка результатов подхода из статьи: https://www.researchgate.net/publication/320426354_Knowledge_based_Fundamental_and_Harmonic_Frequency_Detection_in_Polyphonic_Music_Analysis"""

evaluate_results(Y[:,:B.shape[1]],B)

print(TP)

import matplotlib.pyplot as plt
plt.figure()
#plt.imshow(H_v, aspect='auto', origin='lower')
plt.imshow(B[:,138:150], aspect='auto', origin='lower')
plt.colorbar()
plt.title("Activation matrix H")
plt.xlabel("Time frames")
plt.ylabel("Pitch / Component index")
plt.show()

print(B[:,139])